[package]
name = "cliquery"
version = "0.1.0"
edition = "2021"
authors = ["Toi-même <ta@mail>"]
license = "MIT"
description = "Version Rust autonome et sécurisée de ShellGPT."
readme = "README.md"
repository = ""  # à remplir si besoin
default-run = "cliquery"

[dependencies]
