[package]
name = "cliquery"
version = "0.1.0"
edition = "2025"
authors = ["binary-grunt <codegrunt@proton.me>"]
license = "MIT"
description = "Version Rust autonome et sécurisée de ShellGPT."
readme = "README.md"
repository = ""  # à remplir si besoin
default-run = "cliquery"

[dependencies]
